// <auto-generated />
namespace HospitalManagementSystemDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addedEmailValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedEmailValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "202503100943354_addedEmailValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
